repos:
  - repo: local
    hooks:
      - id: ruff-fix
        name: Linting with Automatic Fixes
        entry: ./scripts/ruff.sh
        args:
          - check
          - --fix
        language: system
        pass_filenames: false
      - id: ruff-format
        name: Formatting
        entry: ./scripts/ruff.sh
        args:
          - format
        language: system
        pass_filenames: false
      - id: pytest-all
        name: Run all tests
        entry: pytest
        args:
          - pydj_auth/tests
          - --maxfail=1
          - --disable-warnings
          - -vv
          - --showlocals
          - --capture=no
          - --log-cli-level=INFO
          - --log-cli-format=%(asctime)s %(levelname)s %(message)s
        language: system
        pass_filenames: false
        always_run: true