repos:
  - repo: local
    hooks:
      - id: ruff-fix
        name: Linting with Automatic Fixes
        entry: ./scripts/ruff.sh
        args:
          - check
          - --fix
        language: system
        pass_filenames: false
      - id: ruff-format
        name: Formatting
        entry: ./scripts/ruff.sh
        args:
          - format
        language: system
        pass_filenames: false
      - id: mypy
        name: Type Checking
        entry: ./scripts/mypy.sh
        language: system
        pass_filenames: false
      - id: pytest-all
        name: Run all tests
        entry: pytest
        args:
          - pydj_auth/tests
          - --maxfail=1
          - --disable-warnings
          - -vv
          - --showlocals
          - -s                 # disable capturing to show all output
        language: system
        pass_filenames: false

